# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name is_check_cpp
#' @title Check if a king is in check
#'
#' @description This function checks if a king is in check. It does this by
#'   checking if any of the opponent's pieces can move to the square currently
#'   occupied by the king.
#'
#' @details The function takes into account the current state of the game and
#'   the color of the king in question. It then checks all possible moves of
#'   the opponent's pieces to see if any could capture the king.
#'
#' @param position A matrix representing the current state of the chess board.
#' @param p An integer indicating the color of the king to check (1 for white,
#'   -1 for black).
#'
#' @return A boolean value indicating whether the king is in check (TRUE) or
#'   not (FALSE).
#'
#' @export
#'
#' @examples
#' # Initialize a chess board
#' position <- position.start()
#' # Check if the white king is in check
#' is_check_cpp(position, 1)
is_check_cpp <- function(position, p) {
    .Call('_bigchess_is_check_cpp', PACKAGE = 'bigchess', position, p)
}

