# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name is_check_cpp
#' @title Test if a king is in check
#'
#' @description This function tests if a king is in check.
#'
#' @details The function looks only at squares from which enemy pieces could
#'   attack the king based on the king's current position. If an attacking
#'   enemy piece is found in one of these squares, the function returns `TRUE`.
#'
#' @param position An 8 x 8 matrix representing the current position.
#' @param p An integer indicating the color of the enemy pieces (1 for white,
#'   -1 for black).
#'
#' @return A Boolean indicating if the king is in check.
#'
#' @export
#'
#' @examples
#' # Initialize a chess board
#' position <- position.start()
#' # Is the white king in check?
#' is_check_cpp(position, -1)
is_check_cpp <- function(position, p) {
    .Call('_bigchess_is_check_cpp', PACKAGE = 'bigchess', position, p)
}

